root: ./

structure:
  readme: README.md

# Exclude files and directories from GitBook
# These won't appear in the published site
exclude:
  # Git and GitHub specific files
  - .git/
  - .github/
  - .gitignore
  - CLAUDE.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - LICENSE

  # Common files to exclude
  - "*.log"
  - .DS_Store
  - node_modules/
