blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/YOUR_USERNAME/CSKnowledgeHub/discussions
    about: For general questions, learning discussions, and community chat

